name = "exelica"
description = "A cute minimal theme"
license = "MIT"
homepage = ""
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
ex_menu = [
    
]
# The theme author info: you!
[author]
name = "Selene"
homepage = "https://triggerhe.art"


